---
services:
  proxy:
    image: traefik:v2.9
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /run/docker.sock:/run/docker.sock
      - ./logins.pass:/etc/traefik/logins.pass
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`deby.stage`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=http
      - traefik.http.routers.dashboard.middlewares=login
      - traefik.http.middlewares.login.basicauth.usersfile=/etc/traefik/logins.pass
        #- traefik.http.middlewares.stripdash.stripprefix.prefixes=/dashboard
        #- traefik.http.routers.dashboard.middlewares=stripdash

networks:
  proxy:
    external: true
