---
x-default: &confshared
  env_file:
    - tz_file

services:
  www:
    image: ${WWW_IMAGE_NAME}:${WWW_IMAGE_VERSION}
    healthcheck:
      test: ["CMD","curl","-f","http://localhost/index.html"]
      interval: 15s
      timeout: 1s
      retries: 2
      # start_period: 60s
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - site:/usr/share/nginx/html
    depends_on:
      - php
    <<: *confshared

  php:
    image: ${PHP_IMAGE_NAME}:${PHP_IMAGE_VERSION}
    volumes:
      - site:/var/www/html
    <<: *confshared

volumes:
  nginx-config:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER_ADDR},vers=4.2
      device: ":/nginx-config"

  site:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER_ADDR},vers=4.2
      device: ":/site"
